### ISSUE TITLE
sai chữ ký 

### ISSUE THREAD

**Issue by ldtrng** [hoanglm4/flutter_hl_vnpay#1]
anh ơi, e nhập vnp_TmnCode với vnp_HashSecret sau khi đăng ký tài khoản nó gửi về email, nhưng mà lúc chạy sang thanh toán nó cứ báo là sai chữ ký là sao vậy ạ

**Comment by hoanglm4** [comment]
Thông tin của em là môi trường test phải k? Nếu đúng post payload lên anh check thử

**Comment by ldtrng** [comment]
hôm qua nó bị xong nay nó hết rồi a, 
Mà anh cho em hỏi làm như nào để khi thanh toán thành công nó quay lại app vậy ạ
