### ISSUE TITLE
Lỗi này là sao nhỉ, ko build dk file aar, mình dùng flutter 2.2.3, dart 2.13.4

### ISSUE THREAD

**Issue by liquid8796** [hoanglm4/flutter_hl_vnpay#2]
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :flutter_hl_vnpay project caused this error: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_hl_vnpay-2.0.0\android\libs\Sdk-release1.17_live.aar

**Comment by thongvo109** [comment]
mình cũng gặp lỗi này

**Comment by thongvo109** [comment]
Đã fix được lỗi này. Tạm thời git clone repo về rồi chỉnh dưới hình là được @liquid8796  
![fixerrorandroid](https://user-images.githubusercontent.com/64881072/135570852-43fff973-c685-4570-86a3-1c3b8d09aa61.jpg)
 
 @hoanglm4  hy vọng bác có thể update lại để mọi người có thể sự dụng. Cảm ơn bác nhiều

**Comment by liquid8796** [comment]
@thongvo109 ok mình cũng đã fix dk lỗi này r, nhưng mình fix cách khác, đó là edit lại minSdkVersion 20 trở lên là đk

**Comment by thongvo109** [comment]
@liquid8796  lúc zalopay mình cũng bị mà chưa fix được cũng nâng minSdk như bác như bất thành nên đã sử dụng native luôn. Nhưng xài lib này lại 1 lần nữa nên mới tìm cách fix triệt để.

**Comment by liquid8796** [comment]
@thongvo109 mà lib vnpay của ông này ko có function bắt returnUrl để xử lí, làm mình phải dùng lib của web view kết hợp vs thuật toán của ổng để xuất ra url request

**Comment by thongvo109** [comment]
@liquid8796 bác có thể cho mình xin contact được không mình cũng chuẩn bị làm cái này tiện trao đổi vài thứ.
